name: My Initial Workflow
on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

  workflow_dispatch:

jobs:
  hellojob:
    name: Hello Test Job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checking Out

    - name: Hello Test Job Render
      run: echo "This is test job"
      shell: bash
